defaults:
  - highscore
  - override writer: cometml
  - _self_

writer:
  project_name: "asvspoof-lcnn"
  workspace: null
  run_name: "lcnn-mel-highscore"
  mode: "online"
  loss_names: ["loss"]
  log_checkpoints: true
  id_length: 32
