defaults:
  - model: lcnn_mel
  - metrics: asvspoof
  - datasets: asvspoof_eval
  - dataloader: asvspoof
  - transforms: asvspoof_mel
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"]
  device: auto
  save_path: "asvspoof_mel"
  output_filename: null
  seed: 14
  from_pretrained: "saved/lcnn-mel-highscore/model_best.pth"
dataloader:
  batch_size: 8
  num_workers: 2
  pin_memory: true
