train:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.Spectrogram
        is_train: true
inference:
  data_object:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.Spectrogram
        is_train: false
